name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: abystoma/external-workflow@3eb7187
      - name: Greetings
        run: echo "$(<greeting.txt)"
